// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBYDBMXZcQA4-apA5DWIfTHW3h_LKPII',
    appId: '1:512660562520:web:abfbf621682fa6b196202d',
    messagingSenderId: '512660562520',
    projectId: 'jumaa-app-2026',
    authDomain: 'jumaa-app-2026.firebaseapp.com',
    storageBucket: 'jumaa-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKQBGHyUDXnslr4A6THIo8-LmTUv02yQ',
    appId: '1:512660562520:android:1ed641b71190a51e96202d',
    messagingSenderId: '512660562520',
    projectId: 'jumaa-app-2026',
    storageBucket: 'jumaa-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpVuAl3SZ-E3pjiSBlxx10ZCl7uL_3Nc',
    appId: '1:512660562520:ios:017ccb22ed3ee60a96202d',
    messagingSenderId: '512660562520',
    projectId: 'jumaa-app-2026',
    storageBucket: 'jumaa-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.apartmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpVuAl3SZ-E3pjiSBlxx10ZCl7uL_3Nc',
    appId: '1:512660562520:ios:017ccb22ed3ee60a96202d',
    messagingSenderId: '512660562520',
    projectId: 'jumaa-app-2026',
    storageBucket: 'jumaa-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.apartmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBYDBMXZcQA4-apA5DWIfTHW3h_LKPII',
    appId: '1:512660562520:web:93b69bae7d4f6b4896202d',
    messagingSenderId: '512660562520',
    projectId: 'jumaa-app-2026',
    authDomain: 'jumaa-app-2026.firebaseapp.com',
    storageBucket: 'jumaa-app-2026.firebasestorage.app',
  );
}
